//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoiDangki
    {
        public static int Iddk { get; internal set; }
        public int IdDk { get; set; }
        public string NoiDk { get; set; }
        public Nullable<int> Phitruocba { get; set; }
    }
}
